jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploying..."

  build:
    runs-on: ubuntu-latest
    needs: deploy  # deploy 작업이 완료된 후 실행됩니다.
    steps:
      - name: Build Step
        run: echo "Building..."

